name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          command_timeout: 10m
          script: |
            set -e
            cd /var/www/hesarak-backend

            # Pull latest changes
            git pull origin main

            # Install dependencies with caching
            pnpm install --frozen-lockfile --prefer-offline

            # Generate types only if collections changed
            git diff --name-only HEAD~1 | grep -qE "collections|payload\.config" && pnpm generate:types || echo "Skipping type generation"

            # Build with optimizations
            export NODE_OPTIONS="--max-old-space-size=768"
            export NEXT_TELEMETRY_DISABLED=1
            pnpm build

            # Restart application
            pm2 restart hesarak-backend || pm2 start pnpm --name "hesarak-backend" -- start
            pm2 save

            # Reload nginx if present
            [ -f /etc/nginx/nginx.conf ] && sudo nginx -s reload || true
