name: Deploy to Digital Ocean

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Digital Ocean Droplet
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: ${{ secrets.DROPLET_PORT }}
          script: |
            # Navigate to project directory
            cd /var/www/hesarak-backend || cd ~/hesarak-backend

            # Pull latest changes
            git pull origin main

            # Install dependencies
            pnpm install --frozen-lockfile

            # Generate types
            pnpm generate:types

            # Build the application
            pnpm build

            # Restart the application using PM2
            pm2 restart hesarak-backend || pm2 start pnpm --name "hesarak-backend" -- start

            # Save PM2 process list
            pm2 save

            # Optional: Reload nginx if you're using it as reverse proxy
            sudo nginx -t && sudo systemctl reload nginx || true
